{
 "title": "Cassandra Dashboard",
 "description": "Cassandra Dashboard with Prometheus and jmx_exporter",
 "tags": [
  "cassandra",
  "salt",
  "java",
  "cortex"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(cassandra_table_totaldiskspaceused_count, cluster)"
   },
   {
    "name": "datacenter",
    "query": "label_values(cassandra_table_totaldiskspaceused_count{cluster=\"$cluster\"}, datacenter)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
   },
   {
    "name": "instance",
    "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\",}, instance)"
   },
   { "name": "interval", "query": "1m" },
   {
    "name": "clientrequest",
    "query": {
     "query": "label_values(cassandra_clientrequest_timeouts_count, clientrequest)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"cassandra\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GC Count Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"} - jvm_gc_collection_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"} offset 1m",
     "legendFormat": "{{ instance }} = {{ gc }}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_sum{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) / irate(jvm_gc_collection_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }} - {{ gc }}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "jvm_memory_committed_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed"
    },
    {
     "expr": "jvm_memory_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "jvm_memory_committed_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed"
    },
    {
     "expr": "jvm_memory_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Heap Used (Old Gen)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - committed {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=~\".*[Oo]ld.*\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used - {{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_peak{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - peak"
    },
    {
     "expr": "jvm_threads_daemon{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - daemon"
    },
    {
     "expr": "jvm_threads_current{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - current"
    },
    {
     "expr": "jvm_threads_deadlocked{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - deadlocked"
    }
   ]
  },
  {
   "title": "Direct Buffer Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"direct\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"direct\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Mapped Buffer Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"mapped\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", pool=\"mapped\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"cassandra\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - max"
    },
    {
     "expr": "process_open_fds{job=\"cassandra\", datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - open"
    }
   ]
  },
  {
   "title": "JVM MEMORY DETAIL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap - Eden",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 872 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[eE]den.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 872 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[mM]eta.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "Heap - Survivor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 880 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[sS]urvivor.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Code Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 880 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]ode.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "Heap - Old",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 888 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[oO]ld.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    },
    {
     "title": "NonHeap - Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 888 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - max {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - committed {{ pool }}"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", pool=~\".*[cC]lass.*\"}",
       "legendFormat": "{{ instance }} - used {{ pool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TABLE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1258 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "targets": [
      {
       "expr": "irate(cassandra_table_readlatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1258 },
     "fieldConfig": { "defaults": { "unit": "wpm" } },
     "targets": [
      {
       "expr": "irate(cassandra_table_writelatency_seconds_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}[3m]) * 60",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Read Latency (95%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1264 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Write Latency (95%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1264 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.95\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Read Latency (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1270 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_readlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Write Latency (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1270 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_writelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Read Latency (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1278 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_coordinatorreadlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Write Latency (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1278 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_coordinatorwritelatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Coordinator Scan Latency (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1278 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cassandra_table_coordinatorscanlatency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.999\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Compaction Bytes Written",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1284 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cassandra_table_compactionbyteswritten_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} - cassandra_table_compactionbyteswritten_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"} offset 1m",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Tombstones Scanned In Queries (99.9%)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1284 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cassandra_table_tombstonescannedhistogram{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\", quantile=\"0.999\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "ss tables count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1290 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "cassandra_table_livesstablecount{datacenter=~\"$datacenter\", cluster=~\"$cluster\", instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\"}\r\n",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "Total Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1290 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "mean partition size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1298 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "cassandra_table_mean_partition_size_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}\r\n",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "ss tables per read 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1298 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cassandra_table_sstablesperrangereadhistogram{datacenter=~\"$datacenter\", cluster=~\"$cluster\", instance=~\"$instance\", keyspace=~\"$keyspace\", table=~\"$table\" ,quantile=\"0.99\"}\r\n",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    },
    {
     "title": "mean partition size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1306 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "cassandra_table_max_partition_size_bytes{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}\r\n",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Live Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cassandra_table_livediskspaceused",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Timeouts And Failures For 1 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_timeouts_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m])) * 60",
     "legendFormat": "{{ instance }} - timeout"
    },
    {
     "expr": "sum by (instance) (irate(cassandra_clientrequest_failures_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[5m])) * 60",
     "legendFormat": "{{ instance }} - failure"
    }
   ]
  },
  {
   "title": "RowCache Requests (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(cassandra_cache_requests_count{cache=\"RowCache\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KeyCache Requests  (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(cassandra_cache_requests_count{cache=\"KeyCache\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RowCache Hits(/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(cassandra_cache_hits_count{cache=\"RowCache\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KeyCache Hits  (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(cassandra_cache_hits_count{cache=\"KeyCache\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(cassandra_compaction_bytescompacted_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Compaction Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "irate(cassandra_compaction_completedtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - completed"
    },
    {
     "expr": "irate(cassandra_compaction_pendingtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - pending"
    }
   ]
  },
  {
   "title": "Compaction Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(cassandra_compaction_pendingtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - completed"
    }
   ]
  },
  {
   "title": "Thread Pools Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_threadpools_activetasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Thread Pools Completed Tasks Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(cassandra_threadpools_completedtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Thread Pools Pending Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_threadpools_pendingtasks{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Threadpools Max Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_threadpools_maxpoolsize{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "Threadpools Total Blocked Tasks Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(cassandra_threadpools_totalblockedtasks_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - {{ path }} {{ threadpools }}"
    }
   ]
  },
  {
   "title": "REPAIR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percent Repaired",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cassandra_table_percentrepaired{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\", table=~\"$table\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ table }}"
      }
     ]
    }
   ]
  },
  { "title": "CLIENT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - native"
    },
    {
     "expr": "cassandra_client_connectedthriftclients{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - thrift"
    }
   ]
  },
  {
   "title": "Client Authorization Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(cassandra_client_authsuccess_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - success"
    },
    {
     "expr": "irate(cassandra_client_authfailure_count{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"}[3m]) * 60",
     "legendFormat": "{{ instance }} - failure"
    }
   ]
  },
  {
   "title": "Client Read Latency (99.9%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_seconds{quantile=\"0.999\", clientrequest=\"Read\"}\r\n",
     "legendFormat": "{{ instance }} - {{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Client Write Latency (99.9%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_seconds{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\", quantile=\"0.999\", clientrequest!~\".*Read.*\"}",
     "legendFormat": "{{ instance }} - {{ clientrequest }}"
    }
   ]
  },
  {
   "title": "Client Timeouts And Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(cassandra_clientrequest_timeouts_count{\r\n  clientrequest=~\"$clientrequest\",\r\n  datacenter=~\"$datacenter\",\r\n  cluster=~\"$cluster\",\r\n  instance=~\"$instance\"\r\n}[5m]) * 60\r\n",
     "legendFormat": "{{ clientrequest }} - timeout"
    },
    {
     "expr": "irate(cassandra_clientrequest_failures_count{\r\n  clientrequest=~\"$clientrequest\",\r\n  datacenter=~\"$datacenter\",\r\n  cluster=~\"$cluster\",\r\n  instance=~\"$instance\"\r\n}[5m]) * 60",
     "legendFormat": "{{ clientrequest }} - failure"
    }
   ]
  }
 ]
}